### ISSUE TITLE
Error while searching product using code

### ISSUE THREAD

**Issue by Shanu1515** [Amitbhave/flutter-barcode-search#1]
![Scan error](https://user-images.githubusercontent.com/45606741/88565039-aeb13980-d051-11ea-82ff-1535ebeb599b.jpeg)
Kindly look into this

**Comment by Amitbhave** [comment]
@Shanu1515 , thanks for raising issue.. Can you please provide more details? How to reproduce this issue? What steps did you follow?

**Comment by Shanu1515** [comment]
When I scan a product ,a code appears and then when I click search,then this error appears.Basically I'm not able to get the product name

**Comment by Amitbhave** [comment]
@Shanu1515 did product filter out from the suggestions list? Can you also provide more information like your android API version?

**Comment by Shanu1515** [comment]
No the product was not filtered out using the scanned code.API level 29, minSDKversion:19.

**Comment by Amitbhave** [comment]
Did you clone the repo and follow exact steps? I have actually tested it on android API version 30 as well, and it is working fine.

**Comment by Amitbhave** [comment]
Closing this as not able to reproduce the issue.
