### ISSUE TITLE
Barcode scanner backend

### ISSUE THREAD

**Issue by Layalekiameh** [Amitbhave/flutter-barcode-search#4]
Hello any idea if i can connect this barcode scanner with woocomerce API flutter app...
Thank you

**Comment by Amitbhave** [comment]
@Layalekiameh  Yes why not! I assume this API returns you Future <String> barcode. Use FutureBuilder() to make this API call and then the search and suggestion widgets.

**Comment by Layalekiameh** [comment]
thank you for your reply can u give  me an example on how I do it pls 
thank you

**Comment by Amitbhave** [comment]
@Layalekiameh updated example.
On the 2nd screen, you can actually integrate your API call which returns Future<T>. Try building project and let me know if this solves your query!

**Comment by Amitbhave** [comment]
Example for API call provided.
